CREATE TABLE services (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    service_type TEXT NOT NULL,
    comments TEXT,
    day TEXT NOT NULL,
    best_time_reached VARCHAR(65535) NOT NULL, 
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    date_modified TIMESTAMP DEFAULT now(),
    price VARCHAR(65535) NOT NULL,
    user_id VARCHAR(65535) REFERENCES users(id) ON DELETE CASCADE NOT NULL
);